// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoEJKOa1u3eJxWqXgesVsgT6HIDaaPTI',
    appId: '1:266264047330:web:ae43d87432c7e94eaff8bb',
    messagingSenderId: '266264047330',
    projectId: 'easybezy-dashbord',
    authDomain: 'easybezy-dashbord.firebaseapp.com',
    databaseURL: 'https://easybezy-dashbord-default-rtdb.firebaseio.com',
    storageBucket: 'easybezy-dashbord.appspot.com',
    measurementId: 'G-8HTW8V6252',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYTOZmr77RXH7Hf6jg8qOOn-ql6npbAUM',
    appId: '1:266264047330:android:35071e458bba746faff8bb',
    messagingSenderId: '266264047330',
    projectId: 'easybezy-dashbord',
    databaseURL: 'https://easybezy-dashbord-default-rtdb.firebaseio.com',
    storageBucket: 'easybezy-dashbord.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhy8_uBxqLSA4p0ZqtKxRLFm0oOKoXKI',
    appId: '1:266264047330:ios:0d84d2099113f2c7aff8bb',
    messagingSenderId: '266264047330',
    projectId: 'easybezy-dashbord',
    databaseURL: 'https://easybezy-dashbord-default-rtdb.firebaseio.com',
    storageBucket: 'easybezy-dashbord.appspot.com',
    iosBundleId: 'com.eazypeasy.qrpeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhy8_uBxqLSA4p0ZqtKxRLFm0oOKoXKI',
    appId: '1:266264047330:ios:3593b6a51249018aaff8bb',
    messagingSenderId: '266264047330',
    projectId: 'easybezy-dashbord',
    databaseURL: 'https://easybezy-dashbord-default-rtdb.firebaseio.com',
    storageBucket: 'easybezy-dashbord.appspot.com',
    iosBundleId: 'com.example.qrpeasyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyoEJKOa1u3eJxWqXgesVsgT6HIDaaPTI',
    appId: '1:266264047330:web:b0981681a68e6a31aff8bb',
    messagingSenderId: '266264047330',
    projectId: 'easybezy-dashbord',
    authDomain: 'easybezy-dashbord.firebaseapp.com',
    databaseURL: 'https://easybezy-dashbord-default-rtdb.firebaseio.com',
    storageBucket: 'easybezy-dashbord.appspot.com',
    measurementId: 'G-NXRTS63L9S',
  );

}